In [25]:
import numpy as np
import math

In [2]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

In [11]:
my_list * my_list

TypeError: can't multiply sequence by non-int of type 'list'

In [13]:
(my_array * my_array) + 100

array([101, 104, 109, 116, 125])

# Assignments

In [14]:
# 1
array_1 = np.array([20, 56])
array_2 = np.array([11, 78])
array_3 = np.array([43, 65])

In [21]:
# 2. Combine the arrays to a single array called diameters
diameters = np.concatenate([array_1, array_2, array_3])
diameters

array([20, 56, 11, 78, 43, 65])

In [26]:
# 3. function to calculate a circle
def calc_circle(diameter):
    radius = diameter / 2
    area = (radius ** 2) * math.pi
    return area

In [33]:
calc_circle(20)

314.1592653589793

In [36]:
# 4. 
sizes_circle = calc_circle(diameters)
sizes_circle

array([ 314.15926536, 2463.00864041,   95.03317777, 4778.36242611,
       1452.20120412, 3318.30724035])

In [42]:
# 5. Filter the sizes_circle array for only values above the avarage value of the sizes_circle array.
mean_size = np.mean(sizes_circle)

sizes_circle[sizes_circle > mean_size]

array([2463.00864041, 4778.36242611, 3318.30724035])

In [43]:
# 6. 
def summarize(input_array):
    num_values = len(input_array)
    std_value = np.std(input_array)
    min_value = np.min(input_array)
    max_value = np.max(input_array)
    unique_values = np.unique(input_array)
    num_unique_values = len(unique_values)

    summary_str = f"""
    Values: {num_values}
    Std: {std_value}
    Min: {min_value}
    Max: {max_value}
    Unique: {unique_values}
    Num unique: {num_unique_values}
    
    """

    print(summary_str)

In [44]:
summarize(sizes_circle)


    Values: 6
    Std: 1653.9397199782222
    Min: 95.03317777109125
    Max: 4778.362426110075
    Unique: [  95.03317777  314.15926536 1452.20120412 2463.00864041 3318.30724035
 4778.36242611]
    Num unique: 6
    
    
